=== Kauko/harja/resources/xsd/sampo/outbound/status.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.0 NT beta 2 build Jul 26 2001 (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:complexType name="ErrorInformationType">
		<xs:sequence>
			<xs:element name="Severity">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="FATAL"/>
						<xs:enumeration value="WARNING"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Exception" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="type" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="XOGOutput">

		<xs:complexType>
			<xs:sequence>
				<xs:element name="Object">
					<xs:complexType>
						<xs:attribute name="type" type="xs:string" use="required"/>
						<xs:attribute name="messageId" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Status">
					<xs:complexType>
						<xs:attribute name="state" type="xs:string" use="required"/>
						<xs:attribute name="elapsedTime" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Statistics" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="updatedRecords" type="xs:integer" use="required"/>
						<xs:attribute name="insertedRecords" type="xs:integer" use="required"/>
						<xs:attribute name="failureRecords" type="xs:integer" use="required"/>
						<xs:attribute name="totalNumberOfRecords" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ErrorInformation" type="ErrorInformationType" minOccurs="0"/>
				<xs:element name="Records" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Record" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="KeyInformation">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="column" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="name" type="xs:string" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="ErrorInformation" type="ErrorInformationType"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DeprecationInformation" type="ErrorInformationType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Kauko/harja/test/resurssit/sampo/maksuera_nack.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<XOGOutput xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/status.xsd">
    <Object messageId="ID:6c321b59:1460814e3:14AE0F721A5" type="product"/>
    <Status elapsedTime="0.8 seconds" state="ERROR"/>
    <Statistics failureRecords="0" insertedRecords="0" totalNumberOfRecords="1" updatedRecords="1"/>
    <Records>
        <Record>
            <KeyInformation>
                <column name="ID">6006296</column>
                <column name="name">Indeksit 2014 (LA203736)</column>
                <column name="UNIQUE_NAME">LA203736</column>
            </KeyInformation>
            <ErrorInformation>
                <Severity>FATAL</Severity>
                <Description>OBS unit (P채ivitt채inen kunnossapito) is invalid.
                    OBS unit path (/P채ivitt채inen kunnossapito/Hoito) is invalid.  So, the OBS Association was not made.
                    OBS association has been updated according to financial information.</Description>
            </ErrorInformation>
        </Record>
        <Record>
            <KeyInformation>
                <column name="task"/>
            </KeyInformation>
            <ErrorInformation>
                <Severity>WARNING</Severity>
                <Description>Object: task Attribute: vv_linked_op is required in partition NIKU.ROOT but has no value</Description>
            </ErrorInformation>
        </Record>
    </Records>
</XOGOutput>
